import 'package:flutter/material.dart';
import '../../../core/models/reliability_models.dart';
import '../../../core/services/reliability_service.dart';

/// Phase 25 — Maintenance Recommendations Page
///
/// Shows actionable maintenance advice generated by the self-healing engine,
/// with approve/reject actions. Zero destructive actions — only advisory.
class MaintenanceRecommendationsPage extends StatefulWidget {
  final String homeId;
  final ReliabilityService reliabilityService;

  const MaintenanceRecommendationsPage({
    super.key,
    required this.homeId,
    required this.reliabilityService,
  });

  @override
  State<MaintenanceRecommendationsPage> createState() =>
      _MaintenanceRecommendationsPageState();
}

class _MaintenanceRecommendationsPageState
    extends State<MaintenanceRecommendationsPage> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      widget.reliabilityService.loadMaintenanceRecommendations(widget.homeId);
    });
  }

  Color _priorityColor(ReliabilitySeverity p) => switch (p) {
    ReliabilitySeverity.critical => const Color(0xFFEF4444),
    ReliabilitySeverity.high => const Color(0xFFF97316),
    ReliabilitySeverity.medium => const Color(0xFFF59E0B),
    ReliabilitySeverity.low => const Color(0xFF6B7280),
  };

  String _statusLabel(String status) => switch (status) {
    'PENDING' => 'Pending Review',
    'APPROVED' => 'Approved',
    'REJECTED' => 'Rejected',
    'IN_PROGRESS' => 'In Progress',
    'COMPLETED' => 'Completed',
    _ => status,
  };

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Scaffold(
      backgroundColor: colorScheme.surface,
      appBar: AppBar(
        backgroundColor: colorScheme.surface,
        elevation: 0,
        leading: const BackButton(),
        title: Text(
          'Maintenance',
          style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700),
        ),
      ),
      body: ListenableBuilder(
        listenable: widget.reliabilityService,
        builder: (context, _) {
          final svc = widget.reliabilityService;

          if (svc.loading && svc.maintenanceRecommendations.isEmpty) {
            return const Center(child: CircularProgressIndicator.adaptive());
          }

          final recs = svc.maintenanceRecommendations;

          return RefreshIndicator(
            onRefresh: () =>
                svc.loadMaintenanceRecommendations(widget.homeId),
            child: recs.isEmpty
                ? Center(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(Icons.build_circle_outlined,
                            color: colorScheme.onSurfaceVariant, size: 48),
                        const SizedBox(height: 12),
                        Text(
                          'No maintenance recommendations',
                          style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                        ),
                        const SizedBox(height: 6),
                        Text(
                          'The self-healing engine will surface\nrecommendations when issues are detected.',
                          textAlign: TextAlign.center,
                          style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 13),
                        ),
                      ],
                    ),
                  )
                : ListView.separated(
                    padding: const EdgeInsets.all(20),
                    itemCount: recs.length,
                    separatorBuilder: (_, _) => const SizedBox(height: 12),
                    itemBuilder: (context, index) {
                      final rec = recs[index];
                      final priorityColor = _priorityColor(rec.priority);

                      return Container(
                        decoration: BoxDecoration(
                          color: colorScheme.surfaceContainerHighest.withValues(alpha: 0.4),
                          borderRadius: BorderRadius.circular(18),
                          border: Border.all(
                              color: priorityColor.withValues(alpha: 0.25)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            // Header
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 16, vertical: 12),
                              decoration: BoxDecoration(
                                color: priorityColor.withValues(alpha: 0.07),
                                borderRadius: const BorderRadius.vertical(
                                    top: Radius.circular(18)),
                              ),
                              child: Row(children: [
                                Icon(Icons.build_rounded,
                                    color: priorityColor, size: 18),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    rec.title,
                                    style: theme.textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700),
                                  ),
                                ),
                                Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 8, vertical: 3),
                                  decoration: BoxDecoration(
                                    color: priorityColor.withValues(alpha: 0.15),
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Text(
                                    rec.priority.name.toUpperCase(),
                                    style: TextStyle(
                                        color: priorityColor,
                                        fontSize: 9,
                                        fontWeight: FontWeight.w800),
                                  ),
                                ),
                              ]),
                            ),
                            // Body
                            Padding(
                              padding: const EdgeInsets.all(16),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    rec.description,
                                    style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 13),
                                  ),
                                  if (rec.actionSteps.isNotEmpty) ...[
                                    const SizedBox(height: 10),
                                    Text(
                                      'Action Steps',
                                      style: theme.textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700),
                                    ),
                                    const SizedBox(height: 6),
                                    ...rec.actionSteps.asMap().entries.map(
                                      (e) => Padding(
                                        padding: const EdgeInsets.only(bottom: 4),
                                        child: Row(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              '${e.key + 1}. ',
                                              style: TextStyle(
                                                color: colorScheme.onSurfaceVariant,
                                                fontSize: 12,
                                                fontWeight: FontWeight.w700,
                                              ),
                                            ),
                                            Expanded(
                                              child: Text(
                                                e.value,
                                                style: TextStyle(
                                                  color: colorScheme.onSurfaceVariant,
                                                  fontSize: 12,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                  const SizedBox(height: 12),
                                  Row(children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 8, vertical: 3),
                                      decoration: BoxDecoration(
                                        color: colorScheme.surfaceContainerHighest,
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: Text(
                                        _statusLabel(rec.status),
                                        style: TextStyle(
                                          color: colorScheme.onSurfaceVariant,
                                          fontSize: 10,
                                        ),
                                      ),
                                    ),
                                    const Spacer(),
                                    Text(
                                      '${rec.createdAt.year}-'
                                      '${rec.createdAt.month.toString().padLeft(2, '0')}-'
                                      '${rec.createdAt.day.toString().padLeft(2, '0')}',
                                      style: TextStyle(
                                        color: colorScheme.onSurfaceVariant,
                                        fontSize: 11,
                                      ),
                                    ),
                                  ]),
                                ],
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
          );
        },
      ),
    );
  }
}
